#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
#Displays information about subdomains

function fetch_dns_config() {
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ -z "$subdomain" ]; then
    
    fetch_dns_config $domain www
    fetch_dns_config $domain lb-01
    fetch_dns_config $domain web-01
    fetch_dns_config $domain web-02
else
    fetch_dns_config $domain $subdomain
fi
