#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Configuration variables
DOMAIN_NAME='yandah1.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    default_backend http_back

backend http_back
    balance roundrobin
    server 427687-web-01 54.165.52.121:80 check
    server 427687-web-02 34.204.81.17:80 check
EOL
sudo sed -i 's|#ENABLED=0|ENABLED=1|' $INIT_FILE
sudo service haproxy restart
