#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it. 

# Get the current date
current_date=$(date +%d-%m-%Y)

# Set the MySQL root password
mysql_root_password="$1"
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
