#!/usr/bin/env bash 
# This Bash script that displays the contect of the file /etc/passwd, using the loop + IFS.

while IFS=':' read -r -a fields;
	do
	echo "The user ${fields{0}} is part of the ${fields[3]} gang, lives in ${fields[5]} and \
rides ${fields[6]}. ${fields[2]}'s place is protected by passcode ${fields[1]}, more \
info about the user here: ${fields[4]}"

done < /etc/passwd;
