#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=0

# Until loop script that is displaying "Best School" 10 times
until [ $counter -eq 10 ]
do
	echo "Best School"
	counter=$((counter+1))
done
