#!/usr/bin/env bash
# Bash script that configures the container to fit;
# nginx must be running as nginx user

# Check if the script is executed with root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root. Exiting..."
    exit 1
fi

# Update Nginx configuration to use the nginx user
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Update Nginx configuration to listen on all active IPs on port 8080
sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default

# Stop any Apache processes if they are running (optional, only if Apache is present)
pkill -9 apache

chmod 644 /etc/nginx/nginx.conf

# Start Nginx
sudo -u nginx service nginx start
