#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080

# Update Nginx configuration to use the nginx user
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf

# Update Nginx configuration to listen on all active IPs on port 8080
sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default

# Stop any Apache processes if they are running (optional, only if Apache is present)
pkill -9 apache
chmod 644 /etc/nginx/nginx.conf

# Start Nginx
sudo -u nginx service nginx start

